version: "3.4"
services:
    mysql:
        image: mysql:5.7
        container_name: laravel-mysql
        volumes:
            - db:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: database
            MYSQL_USER: user
            MYSQL_PASSWORD: secret
        ports:
            - "3306:3306"

    php:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel-php7
        links:
            - mysql
        expose:
            - "9000"
        ports:
            - "9001:9001"
        volumes:
            - ./../:/var/www/html
        environment:
            XDEBUG_CONFIG: remote_host=127.0.0.1

    webserver:
        image: nginx
        container_name: laravel-webserver
        links:
            - php
        volumes:
            - ./../:/var/www/html
            - ./../storage/logs/nginx/:/var/log/nginx
            - ./nginx_conf:/etc/nginx/conf.d/
        ports:
            - "80:80"

volumes:
    db:
