version: "3.4"
services:
    mysql:
        image: mysql:5.7
        container_name: laravel-mysql
        volumes:
            - db:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: 123456
            MYSQL_DATABASE: db
            MYSQL_USER: user
            MYSQL_PASSWORD: 123456
        ports:
            - "3306:3306"

    php:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel-php7
        links:
            - mysql
        ports:
            - "9000:9000"
        volumes:
            - ./../:/var/www/html

    webserver:
        image: nginx
        container_name: laravel-webserver
        links:
            - php
        volumes:
            - ./../:/var/www/html
            - ./../storage/logs/nginx/:/var/log/nginx
            - ./nginx_conf:/etc/nginx/conf.d/
        ports:
            - "80:80"
volumes:
    db:
